0.15.1
AnacondaRecipes/tokenizers-feedstock pull request #9
Opened 2024-02-01 23:22 UTC by psteyer

2024-02-01 23:23 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_cebmc2pak9/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:35: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-02-07 21:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_b6w3zc1pqf/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:35: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-02-09 15:31 UTC, M-Waszkiewicz-Anaconda approved these changes

2024-02-09 15:48 UTC, JeanChristopheMorinPerso reviewed
We need to build for Python 3.12.

2024-02-09 15:48 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>      - wheel
```suggestion
```
You should also remove `setuptools-rust`.

2024-02-09 15:48 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - maturin
```suggestion
    - maturin >=1.0,<2.0
```

2024-02-09 15:48 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - huggingface_hub
```suggestion
    - huggingface_hub >=0.16.4,<1.0
```

2024-02-09 18:53 UTC, Jrice1317 commented on recipe/meta.yaml
>    number: 0
I think it's safe to change the `skip` to `py<37`
See [here](https://github.com/huggingface/tokenizers/blob/v0.15.1/bindings/python/pyproject.toml#L3)

2024-02-09 18:56 UTC, Jrice1317 requested changes
Outside of the changes @JeanChristopheMorinPerso suggested, LGTM!

2024-02-12 12:37 UTC, skupr-anaconda commented on recipe/meta.yaml
>    number: 0
`win32` can be removed as we do not support it

2024-02-12 19:56 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_41a73qbt5_/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:32: missing_wheel: For pypi packages, wheel should be present in the host section
===== Final Report: =====
1 Error and 1 Warning were found

</details>

2024-02-14 14:34 UTC, JeanChristopheMorinPerso approved these changes

2024-02-14 17:55 UTC, Jrice1317 approved these changes

2024-02-19 10:09 UTC, skupr-anaconda approved these changes

2024-02-22 20:29 UTC, merged

2024-02-22 20:30 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_808bsj44ls/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:32: missing_wheel: For pypi packages, wheel should be present in the host section
===== Final Report: =====
1 Error and 1 Warning were found

</details>